version: "3.3"

services:
  database:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=root
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - "27017-27019:27017-27019"
    expose:
      - "27017-27019"
